### PR TITLE
Better Notifications (and Minesweeper optional application)

### PR DESCRIPTION
**Pull request by sbot50**
### Added:
- Mines_light
- Mines_dark

### Edited:
- Pager

### MinesApp:
Normal minesweeper,
Comes in 2 flavors light mode and the superior dark mode.
Click to reveal a tile, double click to flag or unflag a tile.
(Flagged tiles cant be revealed unless unflagged)

### PagerApp:
Edited NotificationApp so it's actually useful.

**Controls:**
Swipe Left/Right: go from old to new notifications (oldest is left)
Swipe Up: go to the next pages of the notification*
Swipe Up (last page of the notification): Remove notification
Swipe Down: go to the previous pages of the notification*
Swipe Down (first page of the notification): Clear all notifications*
Press Button: go back to watch face (previous application, but thats always watch face in this case)
*Default behaviour that hasn't changed

**Tweaks:**
- Old notifications don't clear after looking at them
- Look at the oldest notification first
- Scroll through notifications
- Clear individual notifications

#### Sidenote
Yes ik there are commit from other people in this pull request too, why? no clue. If you want me to change that you need to give me a tutorial lol.

### CODE REVIEW

**Comment by sbot50** [comment]
@fgaz So i think you should be able to review it now, this is the only important pull requests, the 2 others are comming in a sec. As for why it says 5 commits, I have 0 clue. But only 1 file edited so that should be correct.

**Comment by sbot50** [comment]
oh i didnt know the other git pushs would go to this pull request... sorry about that

**Comment by sbot50** [comment]
imma update the desc above and ig wait for this to go through before submitting the one where i add the therminal watch face

**Comment by fgaz** [comment]
> As for why it says 5 commits, I have 0 clue.

it's due to the merge commit ("Merge branch 'wasp-os:master' into master"). If you update your branch with `git rebase master` instead, you won't get those.

> oh i didnt know the other git pushs would go to this pull request

you have to use a different branch for each pull request for them to stay separate

**Comment by sbot50** [comment]
> it's due to the merge commit ("Merge branch 'wasp-os:master' into master"). If you update your branch with `git rebase master` instead, you won't get those.
Well, ig it doesn't matter too much right? since it still shows only my edits in the file changes

> you have to use a different branch for each pull request for them to stay separate
Thats... a pain, im just gonna do 1 feature at a time probably lol

**Comment by beardeddude** [comment]
As you may know after the merge of #403 the naming conventions and file placement have changed slightly. See https://wasp-os.readthedocs.io/en/latest/appguide.html#app-naming-conventions-and-placement for details.

Also personal opinion: This should be 2 separate PRs, One for the game and one fore the notification enhancement. Also we probably only need one version of the game. (I look forward to playing it)

**Comment by sbot50** [comment]
> As you may know after the merge of #403 the naming conventions and file placement have changed slightly. See https://wasp-os.readthedocs.io/en/latest/appguide.html#app-naming-conventions-and-placement for details.
> 
> Also personal opinion: This should be 2 separate PRs, One for the game and one for the notification enhancement. Also we probably only need one version of the game. (I look forward to playing it)

well this is gonna be a pain but ok, ill have it at 2 seperate ones in a few days

**Pull request closed without merging**
