### PR TITLE
Update draw565.py

### PR DESCRIPTION
**Pull request by tomchiverton**
Correct order of arguments in docs

### CODE REVIEW

**Comment by fgaz** [comment]
You'll have to sign off your commit, see [the failing check](https://github.com/wasp-os/wasp-os/pull/440/checks?check_run_id=15068556442)

**Comment by tomchiverton** [comment]
Done, but this seems a high barrier to changes because edits can not be made in the Github web interface

**Comment by fgaz** [comment]
Well, the github interface is only good for quick fixes anyway, and it _is_ possible to sign-off from there if you remember to. The sign-off requirement is also mentioned in the contribution docs. Finally, most changes require testing first. So in my opinion it doesn't make much of a difference

**Review by fgaz — APPROVED** [review]
Looks good!

I took the liberty of removing the automated "Update draw565.py" from the commit message

**Comment by fgaz** [comment]
Actually it looks like you dodn't include your e-mail address in the signoff line

**Comment by tomchiverton** [comment]
How do I add this from the gitlab web GUI?
-- 
†øღ

**Comment by fgaz** [comment]
I have no idea. But I think I figured it out. Author and committer metadata did not match due to the first edit being made in the github web interface (one more reason to avoid it). I updated the address to the one matching the author data. It's a fake github email address, but by looking at past commits it looks like that's ok

**Pull request merged**
